apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: real-estate-mlops-ghcr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TomashukAnna/real_estate_mlops.git
    targetRevision: master
    path: k8s/overlays/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: real-estate-mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
